primary:
  persistence:
    enabled: true
    existingClaim: m-pvc
    storageClass: ""
    size: 5Gi
  initContainers:
    - name: clone-sql
      image: alpine/git
      command: ["/bin/sh", "-c"]
      args:
        - rm -rf /bitnami/mariadb/init && chown -R 1001:1001 /bitnami/mariadb && git clone https://github.com/kt-cloudnative2024/init_container /bitnami/mariadb/init
      volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
  lifecycle:
    postStart:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for MariaDB to be ready..."
            until mysqladmin ping -h 127.0.0.1 --silent; do sleep 1; done
            echo "Running init SQL script..."
            mysql -uroot -p$MARIADB_ROOT_PASSWORD < /bitnami/mariadb/init/BI_CSYSCD.sql
